In [15]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('02 Flipkart Full Project/flipkart_clean_data.csv')

In [4]:
df.head()

,uniq_id,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,product_rating,overall_rating,brand,main_category
0,c2d766ca982eca8304150849735ffef9,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,False,0.0,0.0,Alisha,"[""Clothing"
1,7f7036a6d550aaa89d34c77bd39a5e48,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,False,0.0,0.0,FabHomeDecor,"[""Furniture"
2,f449ec65dcbc041b6ae5e6a32717d01b,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,False,0.0,0.0,AW,"[""Footwear"
3,0973b37acd0c664e3de26e97e5571454,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,0.0,0.0,Alisha,"[""Clothing"
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,False,0.0,0.0,Sicons,"[""Pet Supplies"

In [6]:
df["product_category_tree"] = df["product_category_tree"].str.replace('[\[\]"]', '', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\['
<>:1: SyntaxWarning: invalid escape sequence '\['
C:\Users\royni\AppData\Local\Temp\ipykernel_16684\3933388448.py:1: SyntaxWarning: invalid escape sequence '\['
  df["product_category_tree"] = df["product_category_tree"].str.replace('[\[\]"]', '', regex=True)

In [10]:
df.head(5)

,uniq_id,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,product_rating,overall_rating,brand,main_category
0,c2d766ca982eca8304150849735ffef9,Alisha Solid Women's Cycling Shorts,"Clothing >> Women's Clothing >> Lingerie, Slee...",SRTEH2FF9KEDEFGF,999.0,379.0,False,0.0,0.0,Alisha,Clothing
1,7f7036a6d550aaa89d34c77bd39a5e48,FabHomeDecor Fabric Double Sofa Bed,Furniture >> Living Room Furniture >> Sofa Bed...,SBEEH3QGU7MFYJFY,32157.0,22646.0,False,0.0,0.0,FabHomeDecor,Furniture
2,f449ec65dcbc041b6ae5e6a32717d01b,AW Bellies,Footwear >> Women's Footwear >> Ballerinas >> ...,SHOEH4GRSUBJGZXE,999.0,499.0,False,0.0,0.0,AW,Footwear
3,0973b37acd0c664e3de26e97e5571454,Alisha Solid Women's Cycling Shorts,"Clothing >> Women's Clothing >> Lingerie, Slee...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,0.0,0.0,Alisha,Clothing
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,Sicons All Purpose Arnica Dog Shampoo,Pet Supplies >> Grooming >> Skin & Coat Care >...,PSOEH3ZYDMSYARJ5,220.0,210.0,False,0.0,0.0,Sicons,Pet Supplies

In [9]:
df['main_category'] = df['product_category_tree'].str.split('>>').str[0].str.strip()

In [18]:
df["main_category"].unique()

array(['Clothing', 'Furniture', 'Footwear', 'Pet Supplies',
       'Eternal Gandhi Super Series Crystal Paper Weight...',
       'Pens & Stationery', 'Sports & Fitness',
       'Beauty and Personal Care',
       'Bengal Blooms Rose Artificial Plant  with Pot (3...',
       'Bags, Wallets & Belts', 'Home Decor & Festive Needs',
       'Automotive', 'Tools & Hardware',
       "Vishudh Printed Women's Straight Kurta",
       "Vishudh Printed Women's Anarkali Kurta",
       'BuildTrack PIR Wireless Motion Sensor - One Swit...',
       'Skayvon SUMMERSIBLE SINGLE PHASE PUMP CONTROLLER...',
       "MASARA Solid Women's Straight Kurta",
       'Skayvon SUBMERSIBBLE THREE PHASE PUMP CONTROLLER...',
       'Behringer Xenyx 502 Analog Sound Mixer',
       "Noor Embroidered Women's Straight Kurta",
       "Libas Printed Women's A-line Kurta",
       "Libas Printed Women's Anarkali Kurta", 'Home Furnishing',
       'Baby Care', 'Mobiles & Accessories', 'Food & Nutrition',
       'Watches', 'Toys & School Supplies', 'Jewellery',
       'Cellbazaar Blackberry 8520 WHITE LCD LCD (YIT-562)',
       'Dressberry Gold Synthetic  Clutch',
       'Mast & Harbour Black Synthetic  Clutch',
       "Sisel Printed Poly Cotton Women's Stole",
       'Knight Ace Kraasa Sports Running Shoes, Cycling ...',
       "Indistar Self Design Viscose Women's Stole",
       'Glacier Running Shoes', 'Dressberry Black Synthetic  Clutch',
       'Asics Gel-Cumulus 17 Running Shoes',
       'Mast & Harbour Gold Synthetic  Clutch',
       'Asics Gel-Kayano 22 Running Shoes',
       'Dressberry Orange Synthetic  Clutch',
       'Dressberry Green Synthetic  Clutch', 'Escan Lace Up',
       "Nine Maternity Wear Women's Fit and Flare Dress", 'Sunglasses',
       'Kitchen & Dining', 'Home & Kitchen', 'Computers',
       'Cameras & Accessories', 'ANAND ARCHIES Girls Flats',
       'ANAND ARCHIES Girls Wedges',
       'Prime Printed 8 Seater Table Cover (Multicolor, ...',
       'Health & Personal Care Appliances',
       'Speedwav 240437 Sun Shade For Hyundai i10 (Dashb...',
       "Vitamins Solid Baby Girl's Basic Shorts", 'Gaming',
       'Home Improvement', 'Sumo Baby Walker (Red)',
       "Kombee Girl's Printed Red, Pink Top & Capri Set",
       'NEWGEN TECH EO-HS3303 218 Wired Headset (White)',
       'Automation & Robotics',
       'K&P Dr.Ambedkar Large 04 Showpiece  -  19 cm (Po...',
       'K&P Lord Ganesha Large 03 Showpiece  -  19 cm (P...',
       'Adidas IND PRO THI GUA Thigh Guard (White, Blue,...',
       'Bootwale Bellies',
       'clickforsign Avoid Contanimation Wash your Hands...',
       'Treppe Bellies', 'Kanvas Bellies', 'Klaur Melbourne Bellies',
       'Clickforsign Vehicles parked Illegally will be t...',
       'clickforsign Sound horn Before entering Emergenc...',
       "kem Flow Gold skinny Fit Baby Girl's Blue Jeans",
       'Carbanao Chrome Grill Chevrolet Cruze Car Grill ...',
       'Oddy RS 1.5 X 2 100 Sheets Self Stick Reposition...',
       'Synergy SFJB0105 Grocery Bag (Blue)',
       'SHOPOJ White Paper Sky Lantern (80 cm X 34 cm, P...',
       "SUPERMOD Men's Brief", "Lilliput Top Baby Girl's  Combo",
       'Frabjous German silver Rings For Women Alloy Zir...',
       'Zevrr Sterling Silver Swarovski Zirconia Platinu...',
       'Rasav Jewels Yellow Gold Diamond 18 K Ring',
       'Royal Seal Creations 40 ST COLOR Silver Zircon N...',
       'Home Entertainment',
       "ANASAZI Casual 3/4 Sleeve Solid Women's Top",
       'INVENTURE RETAIL Nail Cutter',
       "Fabpoppy Printed Women's Jumpsuit",
       'Power Smart Quick Charging Pack For PAN CGR-DU-2...',
       'Gking Hand Stiched Steering Cover For Maruti Ert...',
       'GM Power mate 4 Strip Surge Protector (White)',
       'Shrih SH-0192 Wired USB Flexible Keyboard (Red)',
       "Threads & Pals Full Sleeve Printed, Solid Men's ...",
       "Threads & Pals Full Sleeve Self Design Men's Swe...",
       'Gking Hand Stiched Steering Cover For Renault Sc...',
       'Power Smart Quick Charging Pack For PAN CGR-D28 ...',
       'xy decor Cotton Sofa Cover (white Pack of 6)',
       'Favourite BikerZ 3514 RAD air filter Ionic Air F...',
       "Little Stars Girl's A-line Multicolor Dress",
       'Wearable Smart Devices',
       'The Crazy Me 1 Compartments Eco-Friendly leather...',
       "Laser X Checkered Men's Boxer (Pack of 4)",
       "E'Hiose Girl's Leggings (Pack of 6)",
       'Lucky Thailand GL/ LG30 Glass (300 ml, Clear, Pa...',
       'Ocean GP/Pyramid Glass (300 ml, Clear, Pack of 12)',
       'Wella Elements Leight Weight Renewing Conditione...',
       'Pu-Good Women Flats', 'Olvin Aviator Sunglasses',
       "TSG Breeze Printed Women's Round Neck Multicolor...",
       'Pout Brass Bangle', 'classyworld Brass Cufflink (Silver-01)',
       "HANS Men's Crew Length Socks",
       "TIMBERLAKE Slim Fit Fit Women's Brown Jeans",
       'Olvin Oval Sunglasses',
       'Urban Girl Foundation Brush (Pack of 12)',
       'FEET FLOW Women Flats', 'Jazz Eyewears Over-sized Sunglasses',
       "Miss Wow Slim Fit Women's Blue Jeans",
       'Dilan Jewels Alloy Zircon 18K Yellow Gold Bangle...',
       'SMART TRADERS Women Wedges', "Clovia Women's Full Coverage Bra",
       'Olvin Wayfarer Sunglasses',
       "PrivateLifes MasterPiece Women's Push-up Bra",
       'COIRFIT Single Coir Mattress', "Clovia Women's T-Shirt Bra",
       "Spa Culture Fit Fit Women's Black Jeans",
       "run of luck Solid Women's Round Neck Dark Blue T...",
       'SAY UV Sterilizer Solid Filter Cartridge (0, Pac...',
       'Urban Girl Foundation Brush (Pack of 7)',
       "Legmark Slim Fit Women's Light Blue Jeans",
       'Siyas Collection Lac Cubic Zirconia Bangle Set (...',
       "Dassler Slim Fit Women's Multicolor Jeans",
       "piftif Women's Sports Bra", 'REMSON INDIA Women Flats',
       "killys Men's Solid No Show Socks", 'INDILEGO Women Flats',
       'Firangi Cotton, Polyester Free Floor Mat Firangi...',
       "TIMBERLAKE Slim Fit Fit Women's Red Jeans",
       "Starsy Solid Women's Round Neck Green T-Shirt",
       "Oly Two Fit Fit Women's Black Jeans",
       'Olvin Rectangular Sunglasses', "soie Fashion Women's Sports Bra",
       "Auraa Men's, Women's Solid No Show Socks",
       "e-Fresh Boy's Brief (Pack of 5)",
       "TIMBERLAKE Slim Fit Fit Women's Blue Jeans",
       'NEWGEN TECH EO-HS3303 179 Wired Headset (White)',
       "Attitude Printed Women's Round Neck Black T-Shirt",
       'Kalpaveda Copper Bowl (Gold, Pack of 1)', 'Walkline Slippers',
       'D&D Women Flats', "e-Fresh Baby Boy's Brief (Pack of 10)",
       'NEWGEN TECH EO-HS3303 58 Wired Headset (White)',
       "Ajaero Slim Fit Women's Dark Blue Jeans",
       "Ruhi's Creations Cotton Floral King sized Double...",
       'SAY Thread Wounded Candle 10\\ Set of 4 pcs Solid...',
       "The Cotton Company Solid Women's Polo Neck Pink ...",
       'Samprada Modern art Tapestry (Black, Pink)',
       'Naaz Dart game Board Game',
       "Oly Two Fit Fit Women's Dark Blue Jeans",
       "Camey Men's Quarter Length Socks",
       "fourgee Slim Fit Women's Blue Jeans",
       'classyworld Brass Cufflink (Grey-02)',
       "Viral Girl Women's Full Coverage Bra",
       'Wellon Fittings set (16 pieces) for RO Water Pur...',
       'Urban Girl Foundation Brush (Pack of 10)',
       'Amita Home Furnishing Cotton Printed Single Beds...',
       'Impala Alloy Cufflink (White)',
       "Ruhi's Creations Polyester Silk Blend Cartoon Ki...",
       'Naaz 2 in 1 Paper Quilling Board Game',
       "Starsy Printed Women's Round Neck Black T-Shirt",
       "Fly U Slim Fit Fit Women's Brown Jeans",
       'Crafty Hands Kutchchi Mirrorwork Tapestry (Maroon)',
       "tadd Men's, Women's Ankle Length Socks",
       "Dolz Slim Fit Fit Women's Brown Jeans",
       'Shrih Toe & Foot Protector Pain Relief Pad (Pack...',
       "LondonHouze Printed Women's Round Neck Grey T-Shirt",
       "Legmark Slim Fit Women's Blue Jeans",
       'Linzina Fashions LIN-HOSS-1.5 Faucet Set',
       "soie Fashion Women's Full Coverage Bra",
       "Clovia Women's Plunge Bra", 'Foot Candy Women Flats',
       'Amita Home Furnishing Cotton Floral Single Bedsh...',
       "883 Police Full Sleeve Solid Men's Jacket",
       'Style World Women Flats', 'Just Wow Women Flats',
       'SMART TRADERS Women Flats',
       "Ruhi's Creations Cotton Cartoon King sized Doubl...",
       'SJ Bushnell 122/1000M Binoculars (36 mm, Black)',
       'SJ Barstel 56m / 1000m Binoculars (30 mm, Black)',
       'SJ Comet Zoom DPSI Binoculars (30 mm, Black)',
       'Pia International 10X70X70 WITH ZOOM SAKURA Bino...',
       'SHOPOJ Purple Paper Sky Lantern (80 cm X 34 cm, ...',
       'Car vastra 1pcs Car Vastra Honda Beige Backrest ...',
       'SHOPOJ Yellow Paper Sky Lantern (80 cm X 34 cm, ...',
       'SHOPOJ Multicolor Paper Sky Lantern (80 cm X 34 ...',
       'Sj Bushnell 119M / 1000 Binoculars (36 mm, Black)',
       "FIFO Bottom Women's  Combo",
       'Himmlisch 20503 Car Bottle Holder (Plastic)',
       'V&G Professional HD-37 Hair Dryer (Red)',
       'Anuradha Art Stylish Hair Clip (Blue)',
       'Shonaya Printed Bhagalpuri Art Silk Sari',
       'Anuradha Art Stylish Hair Clip (Black)',
       'JUSF2 Black Color Hair Band (Multicolor)',
       'Sonaxo Men Running Shoes',
       'Koie  Battery - For Samsung 7562 Premium Quality...',
       'OEM 170774 Bike Side Stand', 'Kittens Boys Flats',
       'AutoKraftZ Optimum Locking Device For Bajaj Puls...',
       "GALLOWAY skinny Fit Women's Jeans",
       'Dremel 2615.023.132 Plastic Friction Work Bench ...', 'Eyewear',
       'ABEEZ Boys, Men, Girls (Black, Pack of 1)',
       'Joyra Heart Sterling Silver Swarovski Crystal, S...',
       "BLM Casual Printed Women's Kurti",
       "SMART DENIM Solid Women's White Denim Shorts",
       'ATV Pouch for Acer Liquid Z330 (STEEL BLUE)',
       "Be 13 Printed Boy's Round Neck T-Shirt (Pack of 2)",
       'Taurus Black & white Lace Up',
       'Abhinl Fashion Cotton Printed Semi-stitched Salw...',
       "UFO Self Design Round Neck Casual Girl's Sweater",
       "LGRL Women's Leggings", "Breakbounce Men's Vest",
       "UFO Full Sleeve Solid Girl's Jacket",
       'BALAJI EXPORTS Bottled Wine Cooler (9 Bottles)',
       'Siemens 5SL Betagard 5SL MCB (1)',
       'Remax Rm-10000 Remax Vanguard 10000mah 10000 mAh...',
       'Boreal Roller Brush', 'Srajanaa sr114 Travel Shaving Kit (Black)',
       "Selfcare Women's Thong Panty (Pack of 3)",
       'Sugandh Vatika 24 Natural Masala, Sandal Incense...',
       'Arial Morris Women Flats', 'eBooks', 'Zikrak Exim Women Wedges',
       'Zixtro Bug (Black, Backpack)',
       "New Darling Women's Printed Top & Pyjama Set",
       "RajeshFashion Women's Leggings",
       "United Colors of Benetton Girl's Trousers",
       'SRPC BAOER STARWALKER EXECUTIVE ROLLERBALL Pen G...',
       'Kraft Seeds Rosemary Herb (Pack Of 5) Seed (75 p...',
       'Autoplus M AP15 Arm Sleeve (Black)',
       'Autoplus M AP18 Arm Sleeve (Black)',
       'Kraft Seeds Thyme Herbs Seed (200 per packet)',
       'Kraft Seeds Dill Herb Seed (50 per packet)',
       "Leading lady Women's Camisole", "Yo Baby Girl's Trousers",
       'THERISE MD0005 Wired Headset (Pink)',
       'Nut Khut Embroidered Kurta & Churidar',
       "Vinenzia Printed Winter Men's Gloves",
       'Planet Waves Woodstock Strap (Multicolor)',
       'Speedwav 216456 Manual Rear View Mirror (Right, ...',
       'Speedwav 216510 Manual Rear View Mirror (Right, ...',
       'Speedwav 216552 Manual Rear View Mirror (Right, ...',
       'Speedwav 186136 Manual Rear View Mirror (Right, ...',
       'Small Toes Bellies',
       "EASIES Solid Single Breasted Casual Men's Blazer",
       'Clovia Lingerie Set',
       'Speedwav 186926 Royal Enfield 350 Twin Spark LED...',
       'Speedwav 186879 Bajaj Pulsar 200 NS DTS-i LED In...',
       'Household Supplies', "Pazel Slim Fit Men's Jeans",
       'SMART TRADERS Girls Bellies',
       'Corcepts Universal Tablet HD Ultra Clear Transpa...',
       'Areon Luxurious Fragrance Long Lasting Car,Home,...'],
      dtype=object)

In [17]:
df["main_category"].value_counts()

main_category
Clothing                                               6171
Jewellery                                              3522
Footwear                                               1225
Mobiles & Accessories                                  1097
Automotive                                             1010
                                                       ...
Boreal Roller Brush                                       1
Srajanaa sr114 Travel Shaving Kit (Black)                 1
Selfcare Women's Thong Panty (Pack of 3)                  1
Sugandh Vatika 24 Natural Masala, Sandal Incense...       1
Arial Morris Women Flats                                  1
Name: count, Length: 262, dtype: int64

In [19]:
# Remove brackets and quotes properly
df["product_category_tree"] = df["product_category_tree"].str.replace(r'[\[\]"]', '', regex=True)

# Extract main category correctly
df["main_category"] = df["product_category_tree"].str.split(">>").str[0].str.strip()

In [23]:
df = df[df["main_category"].str.len() < 50]

In [24]:
df["main_category"].unique()

array(['Clothing', 'Furniture', 'Footwear', 'Pet Supplies',
       'Pens & Stationery', 'Sports & Fitness',
       'Beauty and Personal Care', 'Bags, Wallets & Belts',
       'Home Decor & Festive Needs', 'Automotive', 'Tools & Hardware',
       "Vishudh Printed Women's Straight Kurta",
       "Vishudh Printed Women's Anarkali Kurta",
       "MASARA Solid Women's Straight Kurta",
       'Behringer Xenyx 502 Analog Sound Mixer',
       "Noor Embroidered Women's Straight Kurta",
       "Libas Printed Women's A-line Kurta",
       "Libas Printed Women's Anarkali Kurta", 'Home Furnishing',
       'Baby Care', 'Mobiles & Accessories', 'Food & Nutrition',
       'Watches', 'Toys & School Supplies', 'Jewellery',
       'Dressberry Gold Synthetic  Clutch',
       'Mast & Harbour Black Synthetic  Clutch',
       "Sisel Printed Poly Cotton Women's Stole", 'Glacier Running Shoes',
       'Dressberry Black Synthetic  Clutch',
       'Asics Gel-Cumulus 17 Running Shoes',
       'Mast & Harbour Gold Synthetic  Clutch',
       'Asics Gel-Kayano 22 Running Shoes',
       'Dressberry Orange Synthetic  Clutch',
       'Dressberry Green Synthetic  Clutch', 'Escan Lace Up',
       'Sunglasses', 'Kitchen & Dining', 'Home & Kitchen', 'Computers',
       'Cameras & Accessories', 'ANAND ARCHIES Girls Flats',
       'ANAND ARCHIES Girls Wedges', 'Health & Personal Care Appliances',
       "Vitamins Solid Baby Girl's Basic Shorts", 'Gaming',
       'Home Improvement', 'Sumo Baby Walker (Red)',
       'Automation & Robotics', 'Bootwale Bellies', 'Treppe Bellies',
       'Kanvas Bellies', 'Klaur Melbourne Bellies',
       'Synergy SFJB0105 Grocery Bag (Blue)', "SUPERMOD Men's Brief",
       "Lilliput Top Baby Girl's  Combo", 'Home Entertainment',
       'INVENTURE RETAIL Nail Cutter',
       "Fabpoppy Printed Women's Jumpsuit", 'Wearable Smart Devices',
       "E'Hiose Girl's Leggings (Pack of 6)", 'Pu-Good Women Flats',
       'Olvin Aviator Sunglasses', 'Pout Brass Bangle',
       'classyworld Brass Cufflink (Silver-01)',
       "HANS Men's Crew Length Socks", 'Olvin Oval Sunglasses',
       'FEET FLOW Women Flats', 'Jazz Eyewears Over-sized Sunglasses',
       "Miss Wow Slim Fit Women's Blue Jeans",
       'SMART TRADERS Women Wedges', "Clovia Women's Full Coverage Bra",
       'Olvin Wayfarer Sunglasses', 'COIRFIT Single Coir Mattress',
       "Clovia Women's T-Shirt Bra",
       "Spa Culture Fit Fit Women's Black Jeans",
       'Urban Girl Foundation Brush (Pack of 7)',
       "piftif Women's Sports Bra", 'REMSON INDIA Women Flats',
       "killys Men's Solid No Show Socks", 'INDILEGO Women Flats',
       "Oly Two Fit Fit Women's Black Jeans",
       'Olvin Rectangular Sunglasses', "soie Fashion Women's Sports Bra",
       "e-Fresh Boy's Brief (Pack of 5)",
       'Kalpaveda Copper Bowl (Gold, Pack of 1)', 'Walkline Slippers',
       'D&D Women Flats', "e-Fresh Baby Boy's Brief (Pack of 10)",
       "Ajaero Slim Fit Women's Dark Blue Jeans",
       'Naaz Dart game Board Game',
       "Oly Two Fit Fit Women's Dark Blue Jeans",
       "Camey Men's Quarter Length Socks",
       "fourgee Slim Fit Women's Blue Jeans",
       'classyworld Brass Cufflink (Grey-02)',
       "Viral Girl Women's Full Coverage Bra",
       'Impala Alloy Cufflink (White)',
       'Naaz 2 in 1 Paper Quilling Board Game',
       "Fly U Slim Fit Fit Women's Brown Jeans",
       "tadd Men's, Women's Ankle Length Socks",
       "Dolz Slim Fit Fit Women's Brown Jeans",
       "Legmark Slim Fit Women's Blue Jeans",
       "soie Fashion Women's Full Coverage Bra",
       "Clovia Women's Plunge Bra", 'Foot Candy Women Flats',
       'Style World Women Flats', 'Just Wow Women Flats',
       'SMART TRADERS Women Flats', "FIFO Bottom Women's  Combo",
       'V&G Professional HD-37 Hair Dryer (Red)',
       'Anuradha Art Stylish Hair Clip (Blue)',
       'Anuradha Art Stylish Hair Clip (Black)',
       'Sonaxo Men Running Shoes', 'OEM 170774 Bike Side Stand',
       'Kittens Boys Flats', "GALLOWAY skinny Fit Women's Jeans",
       'Eyewear', "BLM Casual Printed Women's Kurti",
       'Taurus Black & white Lace Up', "LGRL Women's Leggings",
       "Breakbounce Men's Vest", "UFO Full Sleeve Solid Girl's Jacket",
       'Siemens 5SL Betagard 5SL MCB (1)', 'Boreal Roller Brush',
       'Arial Morris Women Flats', 'eBooks', 'Zikrak Exim Women Wedges',
       'Zixtro Bug (Black, Backpack)', "RajeshFashion Women's Leggings",
       'Autoplus M AP15 Arm Sleeve (Black)',
       'Autoplus M AP18 Arm Sleeve (Black)',
       "Leading lady Women's Camisole", "Yo Baby Girl's Trousers",
       'THERISE MD0005 Wired Headset (Pink)',
       'Nut Khut Embroidered Kurta & Churidar',
       "Vinenzia Printed Winter Men's Gloves", 'Small Toes Bellies',
       'Clovia Lingerie Set', 'Household Supplies',
       "Pazel Slim Fit Men's Jeans", 'SMART TRADERS Girls Bellies'],
      dtype=object)

In [39]:
df["main_category"].value_counts().head(60)

main_category
Clothing                             6171
Jewellery                            3522
Footwear                             1225
Mobiles & Accessories                1097
Automotive                           1010
Home Decor & Festive Needs            927
Beauty and Personal Care              709
Home Furnishing                       700
Kitchen & Dining                      645
Computers                             573
Watches                               528
Baby Care                             481
Tools & Hardware                      387
Toys & School Supplies                329
Pens & Stationery                     313
Bags, Wallets & Belts                 264
Furniture                             180
Sports & Fitness                      166
Home Improvement                       79
Cameras & Accessories                  72
Health & Personal Care Appliances      43
Sunglasses                             40
Gaming                                 35
Pet Supplies                           29
Home & Kitchen                         24
Home Entertainment                     19
eBooks                                 15
Name: count, dtype: int64

In [37]:
category_counts = df["main_category"].value_counts()
valid_categories = category_counts[category_counts > 10].index

df = df[df["main_category"].isin(valid_categories)]

In [40]:
df.head()

,uniq_id,product_name,product_category_tree,pid,retail_price,discounted_price,is_FK_Advantage_product,product_rating,overall_rating,brand,main_category
0,c2d766ca982eca8304150849735ffef9,Alisha Solid Women's Cycling Shorts,"Clothing >> Women's Clothing >> Lingerie, Slee...",SRTEH2FF9KEDEFGF,999.0,379.0,False,0.0,0.0,Alisha,Clothing
1,7f7036a6d550aaa89d34c77bd39a5e48,FabHomeDecor Fabric Double Sofa Bed,Furniture >> Living Room Furniture >> Sofa Bed...,SBEEH3QGU7MFYJFY,32157.0,22646.0,False,0.0,0.0,FabHomeDecor,Furniture
2,f449ec65dcbc041b6ae5e6a32717d01b,AW Bellies,Footwear >> Women's Footwear >> Ballerinas >> ...,SHOEH4GRSUBJGZXE,999.0,499.0,False,0.0,0.0,AW,Footwear
3,0973b37acd0c664e3de26e97e5571454,Alisha Solid Women's Cycling Shorts,"Clothing >> Women's Clothing >> Lingerie, Slee...",SRTEH2F6HUZMQ6SJ,699.0,267.0,False,0.0,0.0,Alisha,Clothing
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,Sicons All Purpose Arnica Dog Shampoo,Pet Supplies >> Grooming >> Skin & Coat Care >...,PSOEH3ZYDMSYARJ5,220.0,210.0,False,0.0,0.0,Sicons,Pet Supplies

In [41]:
len(df)

19583

In [45]:
df["main_category"].nunique()

27

In [49]:
df["main_category"].value_counts().head(27)

main_category
Clothing                             6171
Jewellery                            3522
Footwear                             1225
Mobiles & Accessories                1097
Automotive                           1010
Home Decor & Festive Needs            927
Beauty and Personal Care              709
Home Furnishing                       700
Kitchen & Dining                      645
Computers                             573
Watches                               528
Baby Care                             481
Tools & Hardware                      387
Toys & School Supplies                329
Pens & Stationery                     313
Bags, Wallets & Belts                 264
Furniture                             180
Sports & Fitness                      166
Home Improvement                       79
Cameras & Accessories                  72
Health & Personal Care Appliances      43
Sunglasses                             40
Gaming                                 35
Pet Supplies                           29
Home & Kitchen                         24
Home Entertainment                     19
eBooks                                 15
Name: count, dtype: int64

In [ ]:
df.to_csv("flipkart_clean_final.csv", index=False)

In [50]:
df.to_csv('flipkart_final_clean.csv', index = False)